### ISSUE TITLE
more architecture support required (raspberry)

### ISSUE THREAD

**Issue by axute** [lancachenet/monolithic#112]
### Describe the issue you are having
I would like to take the stack with me to the next LAN party, on a Raspberry (**arm64**) with an external USB. Unfortunately, **amd64** is only available for docker images.

### How are you running the container(s)

how in documentation is described

### DNS Configuration

not possible

### Output of container(s)

not possible

**Comment by unspec** [comment]
We don't currently support any alternative architectures because we generally find that almost all LAN parties need something with more performance than a raspberrypi can provide and so are using amd64 based machines as their caching servers.

It's possible we'll add additional support in the future, but its not currently something we are working on.

There is an unofficial arm64 port maintained here: https://github.com/jrcichra/lancache-rpi -- i can't comment personally on how well it works or not, but i believe people have had some success.

**Comment by axute** [comment]
Thank you for this answer. I will try this thirdparty port ;-)

Regarding the performance, a Raspberry PI 4 (8GB Memory) has very good performance and in terms of network I already have DNS service (pihole) and nginx (reverse proxy manager) running on an RPI 3 B+. Runs very fast and has network-technically very good performance.

**Comment by MathewBurnett** [comment]
While they have many uses and we all love a pi, the performance required at scale includes a large raid array of disks with fast read/write access and alot of memory. This is not where the pi is useful.

**Comment by Ancient123** [comment]
> the performance required at scale includes a large raid array of disks with fast read/write access and alot of memory

A few gigs of memory and a single NVME SSD drive will work fine for anyone running 10G or 1G connections to the cache server. Which is most LAN centers and events.

Hell if your connection is less than 1G a Pi4 and a good large SSD is going to be *JUST FINE*. So the Pi is absolutely a valid choice.

Not mentioning there are more ARM64 devices than *just* the Pi.

**Comment by YowaC** [comment]
I built the 3rd party port on a raspi 4 with 4GB RAM and it worked very well with 4 old random SATA6 HDDs in a big lvm pool (HDDS are 1 3TB 1 1TB and 2 0,5TB = 4,55TB netto capacity) and a USB3.0 4bay enclosure for them i got about 12,5 MB/s download speed non cached (my internet connection speed) and about 120 MB/s from cached content directly (so full 1gbit from raspi-LAN). This actualy works with a pihole as local dns-server between the clients and the lancache, so the lancache is directly connected to the router from my isp (yes this router is crap, but i'm not able to switch it because of some restrictions with hybrid DSL-LTE from Telekom Germany....) and the pihole. The clients connect directly to the pihole (with DHCP and without) and the pihole sends the DNS-queries directly to the lancache-raspi, the lancache then doing his thing and caches or redirect the traffic to public DNS.
So

Client <-> PiHole <-> Lancache <-> Router

It is interesting for me beacause of 5 people at the house with only one internet connection and all using steam and co for gaming stuff etc. (we also often play some games together like AOE2 Definitve Edition). With this setup it speeded up the time, to play together instead of waiting often hours for patches or downloads from new games on every PC.

greetings

yowa
