### ISSUE TITLE
(Request) Support for apt-repos

### ISSUE THREAD

**Issue by rwesterflan** [lancachenet/monolithic#135]
### Describe the issue you are having
Hi! Been using lancache for a while now, and I was thinking - while running a LANparty with a few Ubuntu-servers for games, it would be ideal to cache apt-traffic as well. Seems like Lancache already 'intercepts' http-traffic to adding this sounds simple enough, but maybe it's harder than I think.

**Comment by MathewBurnett** [comment]
Take a look at apt-cacher-ng , it does exactly what you need and is aware of the repository structure. Basically you have a server as the cache and then have all other hosts with a conf in /etc/apt/apt/conf.d that reads something like 

> Acquire::http::Proxy "http://<server ip>:3142";

**Comment by Deanosim** [comment]
If you really want to use nginx to cache apt, I found a guide here with a quick google [http://tdt.rocks/repo_cache_ft_nginx.html](http://tdt.rocks/repo_cache_ft_nginx.html) because with most things someone has already done it before. It could possibly be added but I don't currently know enough about the inner workings to test it, and also have no need because I use apt-cacher-ng.

**Comment by imakiro** [comment]
Hi,

Could this be looked upon once again? We would like to cache apt for a few servers that are gitlab CI runners for different projects. And because sometimes you can't really edit the CI for a specific runner, well, apt caching should be as transparent as possible.
I can invest a bit of time if needed

**Comment by VibroAxe** [comment]
@imakiro apt-cacher-ng is the correct tool for this. It's designed for it and will always do a better job than any lancache instance. Our policy is that this isn't useful in a gaming environment and you should use the correct tool for the job

Sorry
