### ISSUE TITLE
Any interest in caching Apple updates?

### ISSUE THREAD

**Issue by fishscene** [lancachenet/monolithic#174]
Quick question... is there any interest in caching Apple updates?

**Comment by unspec** [comment]
Discussed over here: https://github.com/uklans/cache-domains/issues/191

All apple updates are, as far as we know, HTTPS and thus not suitable to be added to lancache. There are some alternative strategies in the above issue as Apple do have their own caching solution.

In general, we don't tend to see a major problem with Apple updates at LAN events due to not many people bringing them for gaming purposes, so its not a particular priority.

**Comment by yurividal** [comment]
> Quick question... is there any interest in caching Apple updates?

Get an old mac-mini or macbook. Apple Content cache works brilliantly even on these older devices.
