### ISSUE TITLE
Dsn't compare data in a file

### ISSUE THREAD

**Issue by prozaklob** [lancachenet/monolithic#92]
Dsn't compare data in a file. if data in file change - cache machine dont rewrite file.

```
docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 80:80  lancachenet/monolithic:latest
```

**Comment by Lepidopterist** [comment]
Correct.

This cache system is designed for caches that store blocks of data that are immutable.  We specifically do NOT check upstream for a newer version of a file, because there never should be a newer version of  that file.

If you are having a specific problem with a specific CDN, please can you post more information (eg logs showing the issue) and we can investigate.  Otherwise, I will close this issue as 'Not an issue'

**Comment by prozaklob** [comment]
> Correct.
> 
> This cache system is designed for caches that store blocks of data that are immutable. We specifically do NOT check upstream for a newer version of a file, because there never should be a newer version of that file.
> 
> If you are having a specific problem with a specific CDN, please can you post more information (eg logs showing the issue) and we can investigate. Otherwise, I will close this issue as 'Not an issue'

thx for replay.

just i think i  thought that he could work with video files to :)
